Algoritmo "Hospital Santa Aurora - Plantao"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/09/2026
Var
var pediatra, clinico_geral, cirurgiao: caractere
    qtd_ped, qtd_clinico, qtd_cirurgiao: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("| TABELA | TABELA | TABELA |
escreval("| TABELA | TABELA | TABELA |


Fimalgoritmo